name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Data Manager Image
        run: docker build -t myapp-data-manager ./data_manager

      - name: Build Recognition Service Image
        run: docker build -t myapp-recognition-service ./recognition_service

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest tests/
